### PR TITLE
hapus folder ga perlu, perbaiki lint, and add few screen

### PR DESCRIPTION
**Pull request by HyIamJu**
[FL-017] Slicing - Dashboard Screen
[FL-018] Slicing - Tambah Tanaman Feature
[FL-019] Slicing - Informasi Tanaman Feature
[FL-020] Slicing - Informasi Cuaca Feature
[FL-021] Slicing - Delete Tanamanku Feature
[FL-022] Slicing - Search Tanamanku Feature

----Dashboard screen ----
image

----Delete Tanamanku ----
image

----Search Tanaman tersedia ----
image

----Informasi Cuaca ----
image

---- tambah tanaman ----
image

----informasi tanaman ----
image

image
image
image
image

### CODE REVIEW

**Review by Haf1dzsr — APPROVED** [review]
mantap

**Review by adamfzn20 — APPROVED** [review]
mantap👍

**Review by oocengg — APPROVED** [review]
Mantappp

**Review by odesurya — APPROVED** [review]
Mantapppp

**Pull request merged**
