### PR TITLE
Setting slicing

### PR DESCRIPTION
**Pull request by Haf1dzsr**
[FL-007] Slicing - Settings screen
[FL-008] Slicing - Profile screen
[FL-009] Slicing - About Screen
[FL-010] Slicing - Ubah nama
[FL-011] Slicing - Ubah kata sandi
[FL-012] Slicing - Statistik Penanaman
[FL-013] Slicing - Masukan & Saran Screen
[FL-014] Slicing - Pusat Bantuan Screen
[FL-015] Slicing - Detail Jawaban Screen
[FL-016] Slicing - Email Kami Screen

WhatsApp Image 2023-05-26 at 19 33 48
WhatsApp Image 2023-05-26 at 19 35 48(1)
WhatsApp Image 2023-05-26 at 19 36 44

### CODE REVIEW

**Review by oocengg — APPROVED** [review]

**Review by adamfzn20 — APPROVED** [review]
mantap👍

**Review by odesurya — APPROVED** [review]
mantap

**Review by HyIamJu — APPROVED** [review]
anjayyy 😎

**Review by HyIamJu — APPROVED** [review]
anjayyy 😎

**Pull request merged**
