### PR TITLE
Explore monitoring slicing

### PR DESCRIPTION
**Pull request by oocengg**
[FL-023] Slicing - Informasi Detail Tanamanku
[FL-024] Slicing - Overview Tanamanku
[FL-025] Slicing - Progress Tanamanku
[FL-026] Slicing - Edit Nama Tanamanku
[FL-027] Slicing - Add Watering Tanamanku
[FL-028] Slicing - Add Pemupukan Tanamanku
[FL-029] Slicing - Add Weekly Report Tanamanku
[FL-030] Slicing Edit Weekly Report Tanamanku
[FL-031] Slicing - Add Panen Report Tanamanku
[FL-032] Slicing - Add Mati Report Tanamanku

----Informasi Detail Tanamanku Screen----
image
image

----Overview Tanamanku Screen----
image
image

----Progress Tanamanku Screen----
image
image

----Edit Nama Tanamanku Screen----
image
image

----Add Watering & Pemupukan Tanamanku Screen----
image
image

----Add Weekly & Edit Report Tanamanku Screen----
image
image
image
image

----Add Panen Report Tanamanku Screen----
image
image
image

----Add Mati Report Tanamanku Screen----
image
image
image

### CODE REVIEW

**Review by Haf1dzsr — APPROVED** [review]
mantap

**Review by adamfzn20 — APPROVED** [review]
mantap

**Review by odesurya — APPROVED** [review]
mantapp bro

**Review by HyIamJu — APPROVED** [review]
😎🤟👍

**Pull request merged**
