### PR TITLE
Explore monitoring slicing

### PR DESCRIPTION
**Pull request by oocengg**
Menambahkan Slicing pada bagian Explore & Monitoring : 
- Dashboard Screen
- Tanamanku Screen
- Delete Tanamanku Feature
- Informasi Detail Tanamanku
- Overview Tanamanku
- Progress Tanamanku
- Edit Tanamanku
- Weekly Report Tanamanku
- Detail Weekly Report (On Progress)

### CODE REVIEW

**Review by HyIamJu — APPROVED** [review]
GG

**Review by adamfzn20 — APPROVED** [review]
Mantap Mas

**Review by odesurya — APPROVED** [review]

**Review by Haf1dzsr — APPROVED** [review]
ok

**Comment by odesurya** [comment]
keren bro

**Pull request merged**
